# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaperEditForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PaperEditForm(object):
    def setupUi(self, PaperEditForm):
        PaperEditForm.setObjectName("PaperEditForm")
        PaperEditForm.resize(1024, 758)
        self.comboBox_km = QtWidgets.QComboBox(PaperEditForm)
        self.comboBox_km.setGeometry(QtCore.QRect(87, 16, 391, 20))
        self.comboBox_km.setEditable(False)
        self.comboBox_km.setObjectName("comboBox_km")
        self.label = QtWidgets.QLabel(PaperEditForm)
        self.label.setGeometry(QtCore.QRect(500, 18, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PaperEditForm)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.comboBox_stlx = QtWidgets.QComboBox(PaperEditForm)
        self.comboBox_stlx.setGeometry(QtCore.QRect(568, 15, 330, 20))
        self.comboBox_stlx.setObjectName("comboBox_stlx")
        self.pushButton_addItem = QtWidgets.QPushButton(PaperEditForm)
        self.pushButton_addItem.setGeometry(QtCore.QRect(914, 17, 75, 51))
        self.pushButton_addItem.setObjectName("pushButton_addItem")
        self.label_3 = QtWidgets.QLabel(PaperEditForm)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(PaperEditForm)
        self.groupBox.setGeometry(QtCore.QRect(20, 660, 971, 51))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_EditRightPictureAnswer = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_EditRightPictureAnswer.setGeometry(QtCore.QRect(870, 19, 91, 23))
        self.pushButton_EditRightPictureAnswer.setObjectName("pushButton_EditRightPictureAnswer")
        self.lineEdit_zqda = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_zqda.setGeometry(QtCore.QRect(10, 20, 771, 20))
        self.lineEdit_zqda.setObjectName("lineEdit_zqda")
        self.pushButton_saveRightAnswer = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_saveRightAnswer.setGeometry(QtCore.QRect(790, 20, 75, 23))
        self.pushButton_saveRightAnswer.setObjectName("pushButton_saveRightAnswer")
        self.pushButton_testitem = QtWidgets.QPushButton(PaperEditForm)
        self.pushButton_testitem.setGeometry(QtCore.QRect(464, 730, 101, 23))
        self.pushButton_testitem.setObjectName("pushButton_testitem")
        self.groupBox_4 = QtWidgets.QGroupBox(PaperEditForm)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 80, 971, 261))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 50, 721, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_titlepicture = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_titlepicture.setGeometry(QtCore.QRect(10, 20, 701, 141))
        self.graphicsView_titlepicture.setObjectName("graphicsView_titlepicture")
        self.pushButton_EditPictureTitle = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_EditPictureTitle.setGeometry(QtCore.QRect(590, 173, 121, 23))
        self.pushButton_EditPictureTitle.setObjectName("pushButton_EditPictureTitle")
        self.pushButton_titilepicture_zooout = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_titilepicture_zooout.setGeometry(QtCore.QRect(10, 170, 31, 23))
        self.pushButton_titilepicture_zooout.setObjectName("pushButton_titilepicture_zooout")
        self.pushButton_titelpicture_zoomin = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_titelpicture_zoomin.setGeometry(QtCore.QRect(50, 170, 31, 23))
        self.pushButton_titelpicture_zoomin.setObjectName("pushButton_titelpicture_zoomin")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 50, 241, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_AddTitleSubPicture = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_AddTitleSubPicture.setGeometry(QtCore.QRect(137, 172, 91, 23))
        self.pushButton_AddTitleSubPicture.setObjectName("pushButton_AddTitleSubPicture")
        self.graphicsView_titlesubpicture = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView_titlesubpicture.setGeometry(QtCore.QRect(10, 20, 221, 141))
        self.graphicsView_titlesubpicture.setObjectName("graphicsView_titlesubpicture")
        self.pushButton_titilesubpicture_zooout = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_titilesubpicture_zooout.setGeometry(QtCore.QRect(10, 170, 31, 23))
        self.pushButton_titilesubpicture_zooout.setObjectName("pushButton_titilesubpicture_zooout")
        self.pushButton_titelsubpicture_zoomin = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_titelsubpicture_zoomin.setGeometry(QtCore.QRect(50, 170, 31, 23))
        self.pushButton_titelsubpicture_zoomin.setObjectName("pushButton_titelsubpicture_zoomin")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 23, 71, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_tmnr = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_tmnr.setGeometry(QtCore.QRect(70, 20, 811, 20))
        self.lineEdit_tmnr.setObjectName("lineEdit_tmnr")
        self.pushButton_saveTitle = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_saveTitle.setGeometry(QtCore.QRect(890, 19, 75, 23))
        self.pushButton_saveTitle.setObjectName("pushButton_saveTitle")
        self.groupBox_5 = QtWidgets.QGroupBox(PaperEditForm)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 350, 971, 301))
        self.groupBox_5.setObjectName("groupBox_5")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_5)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 961, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 78, 19))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 78, 19))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 78, 19))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 100, 78, 19))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 130, 78, 19))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 78, 19))
        self.label_12.setObjectName("label_12")
        self.pushButton_saveanswer = QtWidgets.QPushButton(self.tab)
        self.pushButton_saveanswer.setGeometry(QtCore.QRect(860, 210, 75, 23))
        self.pushButton_saveanswer.setObjectName("pushButton_saveanswer")
        self.lineEdit_da1 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_da1.setGeometry(QtCore.QRect(70, 10, 871, 20))
        self.lineEdit_da1.setObjectName("lineEdit_da1")
        self.lineEdit_da2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_da2.setGeometry(QtCore.QRect(70, 40, 871, 20))
        self.lineEdit_da2.setObjectName("lineEdit_da2")
        self.lineEdit_da3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_da3.setGeometry(QtCore.QRect(70, 70, 871, 20))
        self.lineEdit_da3.setObjectName("lineEdit_da3")
        self.lineEdit_da4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_da4.setGeometry(QtCore.QRect(70, 100, 871, 20))
        self.lineEdit_da4.setObjectName("lineEdit_da4")
        self.lineEdit_da5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_da5.setGeometry(QtCore.QRect(70, 130, 871, 20))
        self.lineEdit_da5.setObjectName("lineEdit_da5")
        self.lineEdit_da6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_da6.setGeometry(QtCore.QRect(70, 160, 871, 20))
        self.lineEdit_da6.setObjectName("lineEdit_da6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_da1 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_da1.setGeometry(QtCore.QRect(10, 20, 141, 131))
        self.graphicsView_da1.setObjectName("graphicsView_da1")
        self.graphicsView_da2 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_da2.setGeometry(QtCore.QRect(160, 20, 141, 131))
        self.graphicsView_da2.setObjectName("graphicsView_da2")
        self.graphicsView_da3 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_da3.setGeometry(QtCore.QRect(310, 20, 141, 131))
        self.graphicsView_da3.setObjectName("graphicsView_da3")
        self.graphicsView_da4 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_da4.setGeometry(QtCore.QRect(460, 20, 151, 131))
        self.graphicsView_da4.setObjectName("graphicsView_da4")
        self.graphicsView_da5 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_da5.setGeometry(QtCore.QRect(620, 20, 141, 131))
        self.graphicsView_da5.setObjectName("graphicsView_da5")
        self.graphicsView_da6 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_da6.setGeometry(QtCore.QRect(770, 20, 141, 131))
        self.graphicsView_da6.setObjectName("graphicsView_da6")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 78, 19))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(160, 0, 78, 19))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(310, 0, 78, 19))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(460, 0, 78, 19))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(620, 0, 78, 19))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(770, 0, 78, 19))
        self.label_18.setObjectName("label_18")
        self.toolButton_da1 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_da1.setGeometry(QtCore.QRect(120, 160, 31, 21))
        self.toolButton_da1.setObjectName("toolButton_da1")
        self.toolButton_da2 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_da2.setGeometry(QtCore.QRect(270, 160, 31, 21))
        self.toolButton_da2.setObjectName("toolButton_da2")
        self.toolButton_da3 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_da3.setGeometry(QtCore.QRect(420, 160, 31, 21))
        self.toolButton_da3.setObjectName("toolButton_da3")
        self.toolButton_da4 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_da4.setGeometry(QtCore.QRect(580, 160, 31, 21))
        self.toolButton_da4.setObjectName("toolButton_da4")
        self.toolButton_da5 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_da5.setGeometry(QtCore.QRect(730, 160, 31, 21))
        self.toolButton_da5.setObjectName("toolButton_da5")
        self.toolButton_da6 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_da6.setGeometry(QtCore.QRect(880, 160, 31, 20))
        self.toolButton_da6.setObjectName("toolButton_da6")
        self.pushButton_saveanswerpicture = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_saveanswerpicture.setGeometry(QtCore.QRect(830, 210, 75, 23))
        self.pushButton_saveanswerpicture.setObjectName("pushButton_saveanswerpicture")
        self.pushButton_answer_zoomout_1 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomout_1.setGeometry(QtCore.QRect(10, 160, 21, 21))
        self.pushButton_answer_zoomout_1.setObjectName("pushButton_answer_zoomout_1")
        self.pushButton_answer_zoomin_1 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomin_1.setGeometry(QtCore.QRect(30, 160, 21, 21))
        self.pushButton_answer_zoomin_1.setObjectName("pushButton_answer_zoomin_1")
        self.pushButton_answer_zoomin_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomin_2.setGeometry(QtCore.QRect(180, 160, 21, 21))
        self.pushButton_answer_zoomin_2.setObjectName("pushButton_answer_zoomin_2")
        self.pushButton_answer_zoomout_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomout_2.setGeometry(QtCore.QRect(160, 160, 21, 21))
        self.pushButton_answer_zoomout_2.setObjectName("pushButton_answer_zoomout_2")
        self.pushButton_answer_zoomout_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomout_3.setGeometry(QtCore.QRect(310, 160, 21, 21))
        self.pushButton_answer_zoomout_3.setObjectName("pushButton_answer_zoomout_3")
        self.pushButton_answer_zoomin_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomin_3.setGeometry(QtCore.QRect(330, 160, 21, 21))
        self.pushButton_answer_zoomin_3.setObjectName("pushButton_answer_zoomin_3")
        self.pushButton_answer_zoomout_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomout_4.setGeometry(QtCore.QRect(460, 160, 21, 21))
        self.pushButton_answer_zoomout_4.setObjectName("pushButton_answer_zoomout_4")
        self.pushButton_answer_zoomin_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomin_4.setGeometry(QtCore.QRect(480, 160, 21, 21))
        self.pushButton_answer_zoomin_4.setObjectName("pushButton_answer_zoomin_4")
        self.pushButton_answer_zoomout_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomout_5.setGeometry(QtCore.QRect(620, 160, 21, 21))
        self.pushButton_answer_zoomout_5.setObjectName("pushButton_answer_zoomout_5")
        self.pushButton_answer_zoomin_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomin_5.setGeometry(QtCore.QRect(640, 160, 21, 21))
        self.pushButton_answer_zoomin_5.setObjectName("pushButton_answer_zoomin_5")
        self.pushButton_answer_zoomout_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomout_6.setGeometry(QtCore.QRect(770, 160, 21, 21))
        self.pushButton_answer_zoomout_6.setObjectName("pushButton_answer_zoomout_6")
        self.pushButton_answer_zoomin_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_answer_zoomin_6.setGeometry(QtCore.QRect(790, 160, 21, 21))
        self.pushButton_answer_zoomin_6.setObjectName("pushButton_answer_zoomin_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.lineEdit_tmbs = QtWidgets.QLineEdit(PaperEditForm)
        self.lineEdit_tmbs.setGeometry(QtCore.QRect(90, 50, 811, 20))
        self.lineEdit_tmbs.setObjectName("lineEdit_tmbs")

        self.retranslateUi(PaperEditForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PaperEditForm)

    def retranslateUi(self, PaperEditForm):
        _translate = QtCore.QCoreApplication.translate
        PaperEditForm.setWindowTitle(_translate("PaperEditForm", "Form"))
        self.label.setText(_translate("PaperEditForm", "试题类型："))
        self.label_2.setText(_translate("PaperEditForm", "科目："))
        self.pushButton_addItem.setText(_translate("PaperEditForm", "添加"))
        self.label_3.setText(_translate("PaperEditForm", "题目标识："))
        self.groupBox.setTitle(_translate("PaperEditForm", "正确答案"))
        self.pushButton_EditRightPictureAnswer.setText(_translate("PaperEditForm", "编辑图片答案"))
        self.pushButton_saveRightAnswer.setText(_translate("PaperEditForm", "保存"))
        self.pushButton_testitem.setText(_translate("PaperEditForm", "试题检查"))
        self.groupBox_4.setTitle(_translate("PaperEditForm", "题目"))
        self.groupBox_2.setTitle(_translate("PaperEditForm", "题目图片"))
        self.pushButton_EditPictureTitle.setText(_translate("PaperEditForm", "编辑图片题目"))
        self.pushButton_titilepicture_zooout.setText(_translate("PaperEditForm", "+"))
        self.pushButton_titelpicture_zoomin.setText(_translate("PaperEditForm", "-"))
        self.groupBox_3.setTitle(_translate("PaperEditForm", "题目配图"))
        self.pushButton_AddTitleSubPicture.setText(_translate("PaperEditForm", "添加题目配图"))
        self.pushButton_titilesubpicture_zooout.setText(_translate("PaperEditForm", "+"))
        self.pushButton_titelsubpicture_zoomin.setText(_translate("PaperEditForm", "-"))
        self.label_4.setText(_translate("PaperEditForm", "题目内容："))
        self.pushButton_saveTitle.setText(_translate("PaperEditForm", "保存"))
        self.groupBox_5.setTitle(_translate("PaperEditForm", "答案"))
        self.label_7.setText(_translate("PaperEditForm", "答案1："))
        self.label_8.setText(_translate("PaperEditForm", "答案2："))
        self.label_9.setText(_translate("PaperEditForm", "答案3："))
        self.label_10.setText(_translate("PaperEditForm", "答案4："))
        self.label_11.setText(_translate("PaperEditForm", "答案5："))
        self.label_12.setText(_translate("PaperEditForm", "答案6："))
        self.pushButton_saveanswer.setText(_translate("PaperEditForm", "保存答案"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PaperEditForm", "文字答案"))
        self.label_13.setText(_translate("PaperEditForm", "答案1："))
        self.label_14.setText(_translate("PaperEditForm", "答案2："))
        self.label_15.setText(_translate("PaperEditForm", "答案3："))
        self.label_16.setText(_translate("PaperEditForm", "答案4："))
        self.label_17.setText(_translate("PaperEditForm", "答案5："))
        self.label_18.setText(_translate("PaperEditForm", "答案6："))
        self.toolButton_da1.setText(_translate("PaperEditForm", "..."))
        self.toolButton_da2.setText(_translate("PaperEditForm", "..."))
        self.toolButton_da3.setText(_translate("PaperEditForm", "..."))
        self.toolButton_da4.setText(_translate("PaperEditForm", "..."))
        self.toolButton_da5.setText(_translate("PaperEditForm", "..."))
        self.toolButton_da6.setText(_translate("PaperEditForm", "..."))
        self.pushButton_saveanswerpicture.setText(_translate("PaperEditForm", "保存答案"))
        self.pushButton_answer_zoomout_1.setText(_translate("PaperEditForm", "+"))
        self.pushButton_answer_zoomin_1.setText(_translate("PaperEditForm", "-"))
        self.pushButton_answer_zoomin_2.setText(_translate("PaperEditForm", "-"))
        self.pushButton_answer_zoomout_2.setText(_translate("PaperEditForm", "+"))
        self.pushButton_answer_zoomout_3.setText(_translate("PaperEditForm", "+"))
        self.pushButton_answer_zoomin_3.setText(_translate("PaperEditForm", "-"))
        self.pushButton_answer_zoomout_4.setText(_translate("PaperEditForm", "+"))
        self.pushButton_answer_zoomin_4.setText(_translate("PaperEditForm", "-"))
        self.pushButton_answer_zoomout_5.setText(_translate("PaperEditForm", "+"))
        self.pushButton_answer_zoomin_5.setText(_translate("PaperEditForm", "-"))
        self.pushButton_answer_zoomout_6.setText(_translate("PaperEditForm", "+"))
        self.pushButton_answer_zoomin_6.setText(_translate("PaperEditForm", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PaperEditForm", "图片答案"))

