# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SqliteTableEditUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SqliteTableEdit(object):
    def setupUi(self, SqliteTableEdit):
        SqliteTableEdit.setObjectName("SqliteTableEdit")
        SqliteTableEdit.resize(905, 650)
        self.verticalLayoutWidget = QtWidgets.QWidget(SqliteTableEdit)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 841, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.groupBox_table = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_table.setObjectName("groupBox_table")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_table)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 791, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_table = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_table.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_table.setObjectName("horizontalLayout_table")
        self.lineEdit_tablename = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_tablename.setObjectName("lineEdit_tablename")
        self.horizontalLayout_table.addWidget(self.lineEdit_tablename)
        self.checkBox_no_rowid = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_no_rowid.setObjectName("checkBox_no_rowid")
        self.horizontalLayout_table.addWidget(self.checkBox_no_rowid)
        self.checkBox_temporary_table = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_temporary_table.setObjectName("checkBox_temporary_table")
        self.horizontalLayout_table.addWidget(self.checkBox_temporary_table)
        self.verticalLayout_main.addWidget(self.groupBox_table)
        self.groupBox_field = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_field.setObjectName("groupBox_field")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_field)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 52, 791, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_field = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_field.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_field.setObjectName("verticalLayout_field")
        self.horizontalLayout_field_button = QtWidgets.QHBoxLayout()
        self.horizontalLayout_field_button.setObjectName("horizontalLayout_field_button")
        self.pushButton_addfield = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_addfield.setObjectName("pushButton_addfield")
        self.horizontalLayout_field_button.addWidget(self.pushButton_addfield)
        self.pushButton_delfiedl = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_delfiedl.setObjectName("pushButton_delfiedl")
        self.horizontalLayout_field_button.addWidget(self.pushButton_delfiedl)
        self.pushButton_moveup_field = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_moveup_field.setObjectName("pushButton_moveup_field")
        self.horizontalLayout_field_button.addWidget(self.pushButton_moveup_field)
        self.pushButton_movedown_field = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_movedown_field.setObjectName("pushButton_movedown_field")
        self.horizontalLayout_field_button.addWidget(self.pushButton_movedown_field)
        self.verticalLayout_field.addLayout(self.horizontalLayout_field_button)
        self.tableWidget_field = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget_field.setObjectName("tableWidget_field")
        self.tableWidget_field.setColumnCount(0)
        self.tableWidget_field.setRowCount(0)
        self.verticalLayout_field.addWidget(self.tableWidget_field)
        self.verticalLayout_main.addWidget(self.groupBox_field)
        self.groupBox_sql = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_sql.setObjectName("groupBox_sql")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_sql)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 40, 791, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_sql = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_sql.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_sql.setObjectName("verticalLayout_sql")
        self.treeWidget_sql = QtWidgets.QTreeWidget(self.verticalLayoutWidget_3)
        self.treeWidget_sql.setObjectName("treeWidget_sql")
        self.treeWidget_sql.headerItem().setText(0, "1")
        self.verticalLayout_sql.addWidget(self.treeWidget_sql)
        self.verticalLayout_main.addWidget(self.groupBox_sql)
        self.horizontalLayout_okcancel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_okcancel.setObjectName("horizontalLayout_okcancel")
        self.pushButton_ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_okcancel.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_okcancel.addWidget(self.pushButton_cancel)
        self.verticalLayout_main.addLayout(self.horizontalLayout_okcancel)

        self.retranslateUi(SqliteTableEdit)
        QtCore.QMetaObject.connectSlotsByName(SqliteTableEdit)

    def retranslateUi(self, SqliteTableEdit):
        _translate = QtCore.QCoreApplication.translate
        SqliteTableEdit.setWindowTitle(_translate("SqliteTableEdit", "Form"))
        self.groupBox_table.setTitle(_translate("SqliteTableEdit", "表"))
        self.checkBox_no_rowid.setText(_translate("SqliteTableEdit", "无Rowid"))
        self.checkBox_temporary_table.setText(_translate("SqliteTableEdit", "临时表"))
        self.groupBox_field.setTitle(_translate("SqliteTableEdit", "字段"))
        self.pushButton_addfield.setText(_translate("SqliteTableEdit", "添加字段"))
        self.pushButton_delfiedl.setText(_translate("SqliteTableEdit", "删除字段"))
        self.pushButton_moveup_field.setText(_translate("SqliteTableEdit", "上移字段"))
        self.pushButton_movedown_field.setText(_translate("SqliteTableEdit", "下移字段"))
        self.groupBox_sql.setTitle(_translate("SqliteTableEdit", "SQL"))
        self.pushButton_ok.setText(_translate("SqliteTableEdit", "OK"))
        self.pushButton_cancel.setText(_translate("SqliteTableEdit", "Cancel"))

